#!/usr/bin/env bash
# Install (or update) the systemd user units that run the agent overnight.
#
# Usage:
#   ./scripts/systemd/install.sh             # default: fire at 01:00 daily
#   ./scripts/systemd/install.sh 03:30       # custom HH:MM
#   ./scripts/systemd/install.sh --uninstall # remove
#
# Idempotent: safe to re-run after editing config.toml or the agent code.
# Re-running regenerates the unit files with the current paths and reloads
# systemd. The next firing's countdown is printed at the end.

set -euo pipefail

# ── Resolve paths -----------------------------------------------------------

# Project root: parent of scripts/systemd/.
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

UV_PATH="$(command -v uv || true)"
if [[ -z "$UV_PATH" ]]; then
    echo "error: 'uv' not on PATH. Install uv (https://docs.astral.sh/uv/) first." >&2
    exit 1
fi

UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_PATH="$UNIT_DIR/brief-agent.service"
TIMER_PATH="$UNIT_DIR/brief-agent.timer"

# ── Uninstall short-circuit -------------------------------------------------

if [[ "${1:-}" == "--uninstall" ]]; then
    echo "Stopping and disabling brief-agent.timer…"
    systemctl --user disable --now brief-agent.timer 2>/dev/null || true
    rm -f "$SERVICE_PATH" "$TIMER_PATH"
    systemctl --user daemon-reload
    echo "Removed: $SERVICE_PATH"
    echo "Removed: $TIMER_PATH"
    echo "Note: 'sudo loginctl enable-linger' is NOT being undone — disable manually if desired."
    exit 0
fi

# ── Time of run -------------------------------------------------------------

# Default 01:00 local. Override with an HH:MM positional arg.
RUN_TIME="${1:-01:00}"
if ! [[ "$RUN_TIME" =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
    echo "error: time argument must be HH:MM (got: $RUN_TIME)" >&2
    exit 1
fi

# ── Pre-flight --------------------------------------------------------------

if [[ ! -f "$PROJECT_ROOT/config.toml" ]]; then
    echo "warning: config.toml not found at $PROJECT_ROOT/config.toml" >&2
    echo "         The timer will fire, but the agent will exit immediately." >&2
    echo "         Copy config.toml.example to config.toml and edit it first." >&2
fi

if ! systemctl is-enabled --quiet ollama.service 2>/dev/null; then
    echo "warning: ollama.service is not enabled. The overnight run will fail if" >&2
    echo "         Ollama isn't running at fire time." >&2
    echo "         Fix:   sudo systemctl enable --now ollama.service" >&2
fi

# ── Write unit files --------------------------------------------------------

mkdir -p "$UNIT_DIR"

cat > "$SERVICE_PATH" <<EOF
# Generated by scripts/systemd/install.sh. Re-run that script to update.
[Unit]
Description=Open Source Brief Agent — daily papers run
After=network-online.target ollama.service
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory=${PROJECT_ROOT}
ExecStart=${UV_PATH} run python -m agent --mission paper_survey
StandardOutput=journal
StandardError=journal
Nice=10
Restart=no
EOF

cat > "$TIMER_PATH" <<EOF
# Generated by scripts/systemd/install.sh. Re-run that script to update.
[Unit]
Description=Run brief-agent daily at ${RUN_TIME}
Requires=brief-agent.service

[Timer]
OnCalendar=*-*-* ${RUN_TIME}:00
Persistent=true
RandomizedDelaySec=10min
Unit=brief-agent.service

[Install]
WantedBy=timers.target
EOF

echo "Wrote: $SERVICE_PATH"
echo "Wrote: $TIMER_PATH"

# ── Validate syntax ---------------------------------------------------------

if ! systemd-analyze --user verify "$SERVICE_PATH" "$TIMER_PATH" 2>&1; then
    echo "error: systemd-analyze reported issues with the generated units." >&2
    exit 1
fi

# ── Activate ----------------------------------------------------------------

systemctl --user daemon-reload
systemctl --user enable --now brief-agent.timer

# Make user services survive logout. No-op if already enabled.
if ! loginctl show-user "$USER" 2>/dev/null | grep -q 'Linger=yes'; then
    echo
    echo "Note: user lingering is NOT enabled. Without it, the timer dies"
    echo "when you log out. Enable it once with:"
    echo
    echo "    sudo loginctl enable-linger $USER"
    echo
fi

# ── Status ------------------------------------------------------------------

echo
echo "Installed. Next firing:"
systemctl --user list-timers brief-agent.timer --no-pager | tail -n +1
echo
echo "Test manually (runs the real 15-min pipeline, writes to your vault):"
echo "    systemctl --user start brief-agent.service"
echo "    journalctl --user -u brief-agent.service -f"
echo
echo "Edit the run time later:"
echo "    $0 03:30      # to change to 3:30 AM, for example"
echo
echo "Uninstall:"
echo "    $0 --uninstall"
